# Generated by Django 3.1.3 on 2020-11-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201126_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='todo',
            new_name='title',
        ),
    ]
