# Generated by Django 3.1.3 on 2020-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201126_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
